/**
 * `bun run extract`: fetch the pinned upstream source, evaluate its game data, and write
 * deterministic JSON plus types to `src/lib/data/generated/`.
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { buildAchievements } from './datasets/achievements';
import { buildCelestials } from './datasets/celestials';
import { buildChallenges } from './datasets/challenges';
import { buildAutomator, buildH2P, buildProgressStages } from './datasets/docs';
import { buildDilationUpgrades, buildEternity } from './datasets/eternity';
import { buildGlyphs } from './datasets/glyphs';
import { buildInfinityUpgrades } from './datasets/infinity-upgrades';
import { buildPerks } from './datasets/perks';
import { buildRealityUpgrades } from './datasets/reality-upgrades';
import { buildTimeStudies } from './datasets/time-studies';
import { installEnvironment } from './env';
import { ensureUpstream } from './fetch';
import { OUTPUT_DIR, UPSTREAM } from './pin';
import { unresolvedReasons } from './serialize';

/** Output file name (without `.json`) → builder. */
const DATASETS: Record<string, () => object> = {
	achievements: buildAchievements,
	challenges: buildChallenges,
	'infinity-upgrades': buildInfinityUpgrades,
	eternity: buildEternity,
	'time-studies': buildTimeStudies,
	'dilation-upgrades': buildDilationUpgrades,
	'reality-upgrades': buildRealityUpgrades,
	perks: buildPerks,
	glyphs: buildGlyphs,
	celestials: buildCelestials,
	h2p: buildH2P,
	automator: buildAutomator,
	'progress-stages': buildProgressStages
};

const GENERATED_HEADER = `// Generated by \`bun run extract\` from scripts/extract/schema.ts (upstream ${UPSTREAM.repo}@${UPSTREAM.sha}).\n// Do not edit.\n\n`;

/** The schema imports the stage model relative to scripts/extract/; rebase it for the copy. */
function generatedTypes(): string {
	const schema = readFileSync(resolve(import.meta.dir, 'schema.ts'), 'utf8');
	const from = "from '../../src/lib/stages';";
	if (!schema.includes(from))
		throw new Error('schema.ts no longer imports src/lib/stages as expected');
	return GENERATED_HEADER + schema.replace(from, "from '../../stages';");
}

ensureUpstream();
installEnvironment();
rmSync(OUTPUT_DIR, { recursive: true, force: true });
mkdirSync(OUTPUT_DIR, { recursive: true });
for (const [name, build] of Object.entries(DATASETS)) {
	writeFileSync(resolve(OUTPUT_DIR, `${name}.json`), `${JSON.stringify(build(), null, '\t')}\n`);
}
writeFileSync(resolve(OUTPUT_DIR, 'types.ts'), generatedTypes());

const unresolved = [...unresolvedReasons].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
const total = unresolved.reduce((sum, [, count]) => sum + count, 0);
console.log(
	`Extracted ${Object.keys(DATASETS).length} datasets from ${UPSTREAM.repo}@${UPSTREAM.sha}`
);
console.log(`${total} text closures kept as source (state-dependent); first state read:`);
for (const [reason, count] of unresolved) console.log(`  ${String(count).padStart(4)}  ${reason}`);
